[tool.basedpyright]
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType= false
reportUnusedCallResult = false
reportAny = false
reportExplicitAny = false
reportUnknownArgumentType = false
reportAttributeAccessIssue = false
reportUnknownParameterType = false
